[platform_archives.ninja.macos_aarch64]
url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip"
sha256 = "89a287444b5b3e98f88a945afa50ce937b8ffd1dcc59c555ad9b1baf855298c9"
add_prefix = "{{spaces.sysroot}}/bin"
link = "Hard"

[platform_archives.ninja.macos_x86_64]
url = "https://github.com/ninja-build/ninja/releases/download/v1.12.1/ninja-mac.zip"
sha256 = "89a287444b5b3e98f88a945afa50ce937b8ffd1dcc59c555ad9b1baf855298c9"
add_prefix = "{{spaces.sysroot}}/bin"
link = "Hard"

